find_package(LIBNX REQUIRED)
if (NOT LIBNX_FOUND)
    cmake_panic("Unable to detect libnx on this system.")
endif ()

find_package(ZLIB REQUIRED)
if (${ZLIB_FOUND})
    message("ZLIB found : ${ZLIB_VERSION_STRING}")
    message("ZLIB_INCLUDE_DIRS = ${ZLIB_INCLUDE_DIRS}")
    message("ZLIB_LIBRARIES = ${ZLIB_LIBRARIES}")
else()
    message(FATAL_ERROR "ZLIB has not been found.")
endif ()

find_package(Freetype REQUIRED)
if (${FREETYPE_FOUND})
    message("Freetype found : ${FREETYPE_VERSION_STRING}")
    message("FREETYPE_INCLUDE_DIRS = ${FREETYPE_INCLUDE_DIRS}")
    message("FREETYPE_LIBRARIES = ${FREETYPE_LIBRARIES}")
else()
    message(FATAL_ERROR "FREETYPE has not been found.")
endif ()


find_package(BZip2 REQUIRED)
if (${BZIP2_FOUND})
    message("BZIP2 found : ${BZIP2_VERSION_STRING}")
    message("BZIP2_INCLUDE_DIRS = ${BZIP2_INCLUDE_DIRS}")
    message("BZIP2_LIBRARIES = ${BZIP2_LIBRARIES}")
else()
    message(FATAL_ERROR "BZIP2 has not been found.")
endif ()


include_directories(${PROJECT_BINARY_DIR})
include_directories("${PORTLIBS}/include")
include_directories("${LIBNX}/include")
include_directories("${ZLIB_INCLUDE_DIRS}")
include_directories("${FREETYPE_INCLUDE_DIRS}")